In [237]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [238]:
input = 'Electric+Disturbance+Events/DOE_Electric_Disturbance_Events.xlsx'

In [239]:
df_02 = pd.read_excel(input, header=1, sheet_name='2002')

# Overhaul column names for uniformity across different Excel sheets
df_02.rename(columns={'Date':'Date Event Began','Area':'Area Affected',
                      'Number of Customers Affected 1': 'Number of Customers Affected', 
                      'Restoration Time':'Date of Restoration',
                      'Type of Disturbance':'Event Type',
                      'Loss (megawatts)':'Demand Loss (MW)'},
                      inplace=True)
# df_02.drop([0, 2, 5, 7, 9, 12, 16, 21, 23, 28, 36, 37, 38], inplace=True)

df_02.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              34 non-null     object
 1   NERC Region                   23 non-null     object
 2   Time                          23 non-null     object
 3   Area Affected                 25 non-null     object
 4   Event Type                    24 non-null     object
 5   Demand Loss (MW)              19 non-null     object
 6   Number of Customers Affected  23 non-null     object
 7   Date of Restoration           22 non-null     object
dtypes: object(8)
memory usage: 2.6+ KB

In [240]:
# df_02 = df_02.drop([11, 26, 31])
df_02.drop(columns='Time', inplace=True)
df_02['Date Event Began'] = pd.to_datetime(df_02['Date Event Began'], errors='coerce')
df_02 = df_02.dropna(subset=['Date Event Began'])
df_02.reset_index(drop=True, inplace=True)

df_02.head()

,Date Event Began,NERC Region,Area Affected,Event Type,Demand Loss (MW),Number of Customers Affected,Date of Restoration
0,2002-01-30,SPP,Oklahoma,Ice Storm,500,1881134,2002-02-07 12:00:00
1,2002-01-29,SPP,Metropolitan Kansas City Area,Ice Storm,500-600,270000,NaN
2,2002-01-30,SPP,Missouri,Ice Storm,210,95000,2002-02-10 21:00:00
3,2002-02-27,WSCC,California,Interruption of Firm Load,300,255000,2002-02-27 11:35:00
4,2002-03-09,ECAR,Lower Peninsula of Michigan,Severe Weather,190,190000,2002-03-11 12:00:00

In [241]:
df_03 = pd.read_excel(input, header=1, sheet_name='2003')
df_03.rename(columns={'Date':'Date Event Began',
                      'Number of Customers Affected 1': 'Number of Customers Affected',
                      'Restoration':'Date of Restoration',
                      'Type of Disturbance':'Event Type',
                      'Loss (megawatts)':'Demand Loss (MW)'},
                      inplace=True)

df_03.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              87 non-null     object
 1   NERC Region                   65 non-null     object
 2   Time                          63 non-null     object
 3   Area Affected                 73 non-null     object
 4   Event Type                    64 non-null     object
 5   Demand Loss (MW)              60 non-null     object
 6   Number of Customers Affected  60 non-null     object
 7   Date of Restoration           69 non-null     object
dtypes: object(8)
memory usage: 7.4+ KB

In [242]:
df_03['Date Event Began'] = pd.to_datetime(df_03['Date Event Began'], errors='coerce')
df_03 = df_03.dropna(subset=['Date Event Began'])
df_03.reset_index(drop=True, inplace=True)
df_03.drop(columns='Time', inplace=True)

df_03.head()

,Date Event Began,NERC Region,Area Affected,Event Type,Demand Loss (MW),Number of Customers Affected,Date of Restoration
0,2003-01-25,ECAR,"Cincinnati, Ohio",Cyber Threat From Internet,NaN,NaN,"1/26/03, 2:00 a.m."
1,2003-02-27,SERC,"Piedmont, North Carolina",Winter Ice Storm,1000,"over 340,000","3/01/03, 8:00 a.m."
2,2003-04-03,ECAR,Lower Michigan Peninsula,Ice Storm,300,425000,"4/06/03, 5:00 p.m."
3,2003-04-04,NPCC,"New York,",Severe Storm,200-250,160000,"4/05/03, 2:00 p.m."
4,2003-04-15,ERCOT,"Cities of Bryan,",Relaying Malfunction,212,68530,"4/15/03, 2:06 p.m."

In [243]:
df_04 = pd.read_excel(input, header=1, sheet_name='2004')
df_04.rename(columns={'Date':'Date Event Began', 'Number of Customers Affected 1': 'Number of Customers Affected',
                      'Restoration':'Date of Restoration', 'Type of Disturbance':'Event Type', 'Loss (megawatts)':'Demand Loss (MW)'}, inplace=True)

df_04.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              120 non-null    object
 1   NERC Region                   101 non-null    object
 2   Time                          97 non-null     object
 3   Area Affected                 97 non-null     object
 4   Event Type                    97 non-null     object
 5   Demand Loss (MW)              98 non-null     object
 6   Number of Customers Affected  98 non-null     object
 7   Date of Restoration           102 non-null    object
dtypes: object(8)
memory usage: 8.5+ KB

In [244]:
df_04['Date Event Began'] = pd.to_datetime(df_04['Date Event Began'], errors='coerce')
df_04 = df_04.dropna(subset=['Date Event Began'])
df_04.reset_index(drop=True, inplace=True)
df_04.drop(columns='Time', inplace=True)

df_04.head()

,Date Event Began,NERC Region,Area Affected,Event Type,Demand Loss (MW),Number of Customers Affected,Date of Restoration
0,2004-01-01,WECC,Northern California,Winter Storm,170,263000,"1/02/04, 4:00 p.m."
1,2004-01-07,WECC,King County,Snow Storm,150,145000,"1/10/04, 5:00 p.m."
2,2004-01-08,NPCC,"Lake Placid/Saranac, New York",Public Appeal to Reduce Load,100,18600,"1/10/04, 7:00 p.m."
3,2004-01-14,NPCC,"Lake Placid/Saranac, New York",Public Appeal to Reduce Load,100,18600,"1/17/04, 12:00 noon"
4,2004-01-26,SERC,Central South Carolina,Ice Storm,500-700,150000,"1/28/04, 8:00 a.m."

In [245]:
df_05 = pd.read_excel(input, header=1, sheet_name='2005')
df_05.rename(columns={'Date':'Date Event Began', 'Number of Customers Affected 1': 'Number of Customers Affected',
                      'Restoration':'Date of Restoration', 'Type of Disturbance':'Event Type', 'Loss (megawatts)':'Demand Loss (MW)'}, inplace=True)

df_05.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              112 non-null    object
 1   NERC Region                   93 non-null     object
 2   Time                          88 non-null     object
 3   Area Affected                 89 non-null     object
 4   Event Type                    89 non-null     object
 5   Demand Loss (MW)              79 non-null     object
 6   Number of Customers Affected  82 non-null     object
 7   Date of Restoration           94 non-null     object
dtypes: object(8)
memory usage: 8.1+ KB

In [246]:
df_05['Date Event Began'] = pd.to_datetime(df_05['Date Event Began'], errors='coerce')
df_05 = df_05.dropna(subset=['Date Event Began'])
df_05.reset_index(drop=True, inplace=True)
df_05.drop(columns='Time', inplace=True)

df_05.head(10)

,Date Event Began,NERC Region,Area Affected,Event Type,Demand Loss (MW),Number of Customers Affected,Date of Restoration
0,2005-01-04,SPP,Eastern one third of the state of Kansas,Winter Storm,200,211000,"1/14/05, 12:00 p.m."
1,2005-01-05,ECAR,Akron and Mansfield areas,Ice Storm,250,246990,"1/13/05, 6:00 p.m."
2,2005-01-05,ECAR,Indiana Michigan Region - Muncie District,Winter Ice Storm,545,114791,"1/16/05, 11:00 a.m."
3,2005-01-07,WECC,Northern California,Winter Storm,120,442000,"1/10/05, 8:00 a.m."
4,2005-01-19,PR,Island of Puerto Rico,Voltage Reduction,209,NaN,"1/19/05, 9:27 a.m."
5,2005-01-23,PR,Island of Puerto Rico,Voltage Reduction,140,NaN,"1/23/05, 11:24 a.m."
6,2005-01-24,PR,Island of Puerto Rico,Voltage Reduction/Shed Load,225,70717,"1/24/05, 6:50 a.m."
7,2005-01-24,PR,Island of Puerto Rico,Voltage Reduction/Shed Load,385,NaN,"1/24/05, 12:34 p.m."
8,2005-01-29,SERC,Parts of Alabama and Georgia,Ice Storm,100,150000,"1/31/05, 10:00 a.m"
9,2005-01-29,SERC,Georgia,Ice Storm,65 to 100,82000,"1/30/05, 3:00 p.m."

In [247]:
df_06 = pd.read_excel(input, header=1, sheet_name='2006')
df_06.rename(columns={'Date':'Date Event Began', 'Number of Customers Affected 1': 'Number of Customers Affected',
                      'Restoration':'Date of Restoration', 'Type of Disturbance':'Event Type', 'Loss (megawatts)':'Demand Loss (MW)'}, inplace=True)

df_06.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              112 non-null    object
 1   NERC Region                   94 non-null     object
 2   Time                          94 non-null     object
 3   Area Affected                 94 non-null     object
 4   Event Type                    94 non-null     object
 5   Demand Loss (MW)              75 non-null     object
 6   Number of Customers Affected  87 non-null     object
 7   Date of Restoration           94 non-null     object
dtypes: object(8)
memory usage: 7.1+ KB

In [248]:
df_06['Date Event Began'] = pd.to_datetime(df_06['Date Event Began'], errors='coerce')
df_06 = df_06.dropna(subset=['Date Event Began'])
df_06.reset_index(drop=True, inplace=True)
df_06.drop(columns='Time', inplace=True)

df_06.head(10)

,Date Event Began,NERC Region,Area Affected,Event Type,Demand Loss (MW),Number of Customers Affected,Date of Restoration
0,2006-01-14,RFC,"Chester, Montgomery, Delaware, Philadelphia an...",High Winds,--,142315,5:30 p.m. January 16
1,2006-01-18,NPCC,Southern and Central Maine,Severe Storm,75,63000,6:34 p.m. January 18
2,2006-02-04,WECC,"Snohomish County, Washington",Strong Winds,150,123827,12:01 a.m. February 06
3,2006-02-04,WECC,Western Washington,Severe Windstorm,--,140000,8:00 a.m. February 08
4,2006-02-11,RFC,Baltimore Metropolitan and Central Maryland,Major Snow Storm,500,180000,11:00 p.m. February 14
5,2006-02-12,RFC,"Washington DC, Montgomery and Prince Georges C...",Major Snow Storm,300,60000,5:44 p.m. February 14
6,2006-02-12,RFC,Entire Atlantic City Electric territory Southe...,Winter Snow/Ice Storm,80,130000,4:00 p.m. February 14
7,2006-02-12,RFC,Entire Delmarva Power service territory,Winter Snow/Ice Storm,50,58000,7:00 a.m. February 13
8,2006-02-12,RFC,Northern and Northwestern Virginia,Severe Snow Storm,250,126000,2:00 p.m. February 12
9,2006-02-16,RFC,"Muskegon, Michigan easterly to Bay City, Michigan",Severe Thunderstorm/ Snow/Ice Storm,100,252089,11:00 p.m. February 20

In [249]:
df_07 = pd.read_excel(input, header=1, sheet_name='2007')
df_07.rename(columns={'Date':'Date Event Began', ' NERC Region': 'NERC Region', 'Number of Customers Affected 1[1]': 'Number of Customers Affected', 
                      'Restoration':'Date of Restoration', 'Type of Disturbance':'Event Type', 'Loss (megawatts)':'Demand Loss (MW)'}, inplace=True)
df_07.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              97 non-null     object
 1   NERC Region                   80 non-null     object
 2   Time                          80 non-null     object
 3   Area Affected                 80 non-null     object
 4   Event Type                    80 non-null     object
 5   Demand Loss (MW)              62 non-null     object
 6   Number of Customers Affected  68 non-null     object
 7   Date of Restoration           80 non-null     object
dtypes: object(8)
memory usage: 6.2+ KB

In [250]:
df_07['Date Event Began'] = pd.to_datetime(df_07['Date Event Began'], errors='coerce')
df_07 = df_07.dropna(subset=['Date Event Began'])
df_07.reset_index(drop=True, inplace=True)
df_07.drop(columns='Time', inplace=True)

df_07.head(10)

,Date Event Began,NERC Region,Area Affected,Event Type,Demand Loss (MW),Number of Customers Affected,Date of Restoration
0,2007-01-05,PR,Island of Puerto Rico,Voltage Reduction,0,0,11:13 a.m. January 05
1,2007-01-13,MRO,Missouri and Illinois,Ice Storm,NaN,225000,12:00 p.m. January 19
2,2007-01-13,RFC,Eastern and Lower Michigan,Ice Storm,500,129607,4:00 p.m. January 19
3,2007-01-16,WECC,"Snohomish County, Washington",Major Windstorm,260,110433,12:00 a.m. January 17
4,2007-02-13,RFC,Indiana and Southwest Ohio,Ice/Wind Storm,250,367500,12:00 a.m. February 16
5,2007-02-13,RFC,Central Maryland,Winter Storm,400,155183,5:30 a.m. February 17
6,2007-02-24,MRO,"NE quarter of State of Iowa and Rock Island, I...",Ice Storm,210,75000,12:57 a.m. March 04
7,2007-02-24,MRO,Central Iowa and Cedar Rapids areas,Ice Storm,400,140000,11:47 p.m. February 24
8,2007-02-24,RFC,"Cedar Rapids, Iowa",Ice Storm,750,215000,12:47 a.m. February 25
9,2007-02-28,WECC,Northern California,Winter Storm,110,671189,8:45 p.m. March 02

In [251]:
df_08 = pd.read_excel(input, header=1, sheet_name='2008')
df_08.rename(columns={'Date':'Date Event Began', 'Number of Customers Affected 1': 'Number of Customers Affected', 
                      'Restoration':'Date of Restoration', 'Type of Disturbance':'Event Type', 'Loss (megawatts)':'Demand Loss (MW)'}, inplace=True)
df_08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              174 non-null    object
 1   NERC Region                   154 non-null    object
 2   Time                          154 non-null    object
 3   Area Affected                 154 non-null    object
 4   Event Type                    154 non-null    object
 5   Demand Loss (MW)              101 non-null    object
 6   Number of Customers Affected  151 non-null    object
 7   Date of Restoration           161 non-null    object
dtypes: object(8)
memory usage: 12.0+ KB

In [252]:
df_08['Date Event Began'] = pd.to_datetime(df_08['Date Event Began'], errors='coerce')
df_08 = df_08.dropna(subset=['Date Event Began'])
df_08.reset_index(drop=True, inplace=True)
df_08.drop(columns='Time', inplace=True)

df_08.head(10)

,Date Event Began,NERC Region,Area Affected,Event Type,Demand Loss (MW),Number of Customers Affected,Date of Restoration
0,2008-01-04,WECC,Northern California,Winter Storm,500,2606931,5:00 p.m. January 14
1,2008-01-04,WECC,Sacramento County,Severe Storm,300,150000,4:30 p.m. January 04
2,2008-01-29,WECC,"San Francisco Bay Area, California",Exciter Faulted,NaN,-,12:17 p.m. January 29
3,2008-01-29,SERC,"Arkansas, Mississippi, North Louisiana",Severe Thunderstorms,NaN,110000,8:00 a.m February 03
4,2008-01-29,RFC,Southeastern Michigan,Wind/Ice Storm,NaN,86915,6:30 p.m. February 01
5,2008-01-29,RFC,"South Metropolitan Areas of Dayton, OHio",High Winds,380,45000,12:48 a.m. January 30
6,2008-01-30,NPCC,"Western, New York",High Winds,50,54316,2:50 p.m. February 01
7,2008-02-01,WECC,"San Francisco Bay Area, California",Equipment Faulted,NaN,-,7:49 a.m. February 01
8,2008-02-02,WECC,"San Francisco Bay Area, California",Equipment Faulted,NaN,-,4:27 p.m. February 02
9,2008-02-05,SERC,State of Kentucky,Severe Weather,NaN,76000,3:00 a.m. February 06

In [253]:
df_09 = pd.read_excel(input, header=1, sheet_name='2009')
df_09.rename(columns={'Date':'Date Event Began', 'Number of Customers Affected 1': 'Number of Customers Affected', 
                      'Restoration':'Date of Restoration', 'Type of Disturbance':'Event Type', 'Loss (megawatts)':'Demand Loss (MW)'}, inplace=True)
df_09.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              115 non-null    object
 1   NERC Region                   99 non-null     object
 2   Time                          99 non-null     object
 3   Area Affected                 99 non-null     object
 4   Event Type                    99 non-null     object
 5   Demand Loss (MW)              59 non-null     object
 6   Number of Customers Affected  82 non-null     object
 7   Date of Restoration           103 non-null    object
dtypes: object(8)
memory usage: 7.9+ KB

In [254]:
df_09['Date Event Began'] = pd.to_datetime(df_09['Date Event Began'], errors='coerce')
df_09 = df_09.dropna(subset=['Date Event Began'])
df_09.reset_index(drop=True, inplace=True)
df_09.drop(columns='Time', inplace=True)

df_08.head(10)

,Date Event Began,NERC Region,Area Affected,Event Type,Demand Loss (MW),Number of Customers Affected,Date of Restoration
0,2008-01-04,WECC,Northern California,Winter Storm,500,2606931,5:00 p.m. January 14
1,2008-01-04,WECC,Sacramento County,Severe Storm,300,150000,4:30 p.m. January 04
2,2008-01-29,WECC,"San Francisco Bay Area, California",Exciter Faulted,NaN,-,12:17 p.m. January 29
3,2008-01-29,SERC,"Arkansas, Mississippi, North Louisiana",Severe Thunderstorms,NaN,110000,8:00 a.m February 03
4,2008-01-29,RFC,Southeastern Michigan,Wind/Ice Storm,NaN,86915,6:30 p.m. February 01
5,2008-01-29,RFC,"South Metropolitan Areas of Dayton, OHio",High Winds,380,45000,12:48 a.m. January 30
6,2008-01-30,NPCC,"Western, New York",High Winds,50,54316,2:50 p.m. February 01
7,2008-02-01,WECC,"San Francisco Bay Area, California",Equipment Faulted,NaN,-,7:49 a.m. February 01
8,2008-02-02,WECC,"San Francisco Bay Area, California",Equipment Faulted,NaN,-,4:27 p.m. February 02
9,2008-02-05,SERC,State of Kentucky,Severe Weather,NaN,76000,3:00 a.m. February 06

In [255]:
df_10 = pd.read_excel(input, header=1, sheet_name='2010')
df_10.rename(columns={'Date':'Date Event Began', 'Number of Customers Affected 1': 'Number of Customers Affected', 
                      'Restoration':'Date of Restoration', 'Type of Disturbance':'Event Type', 'Loss (megawatts)':'Demand Loss (MW)'}, inplace=True)
df_10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              144 non-null    object
 1   NERC Region                   126 non-null    object
 2   Time                          126 non-null    object
 3   Area Affected                 126 non-null    object
 4   Event Type                    126 non-null    object
 5   Demand Loss (MW)              55 non-null     object
 6   Number of Customers Affected  94 non-null     object
 7   Date of Restoration           126 non-null    object
dtypes: object(8)
memory usage: 9.1+ KB

In [256]:
df_10['Date Event Began'] = pd.to_datetime(df_10['Date Event Began'], errors='coerce')
df_10 = df_10.dropna(subset=['Date Event Began'])
df_10.reset_index(drop=True, inplace=True)
df_10.drop(columns='Time', inplace=True)
df_10.head(10)

,Date Event Began,NERC Region,Area Affected,Event Type,Demand Loss (MW),Number of Customers Affected,Date of Restoration
0,2010-01-06,SERC,Southwest Louisiana,Made Public Appeals,NaN,NaN,6:00 p.m. January 08
1,2010-01-11,FRCC/SERC,Northern and Central Florida,Interruptible Load Shed/Made Public Appeals,NaN,NaN,9:57 a.m. January 11
2,2010-01-18,WECC,Northern and Central California,Severe Storm,290,1700000,8:00 a.m. January 28
3,2010-01-19,WECC,San Francisco,Severe Storm,300,30000,12:24 p.m. January 19
4,2010-01-19,WECC,San Diego and Orange Counties,Severe Storm,2650,50000,3:00 p.m. January 20
5,2010-01-20,WECC,"City of Los Angeles, California",Severe Storm,NaN,147223,6:10 p.m. January 24
6,2010-01-28,SPP,Oklahoma,Ice Storm,NaN,68705,12:00 p.m. February 02
7,2010-02-01,SPP,Oklahoma,Ice Storm/Electrical System Separation,30,0,5:00 p.m. February 01
8,2010-02-05,RFC,Southern NJ,Winter Storm,NaN,221000,4:00 p.m. February 13
9,2010-02-05,SERC,North and South Carolina,Winter Storm,500,74000,5:00 p.m. February 07

In [257]:
df_11 = pd.read_excel(input, header=1, sheet_name='2011')
df_11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321 entries, 0 to 320
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date Event Began              320 non-null    object
 1   Time Event Began              307 non-null    object
 2   Date of Restoration           307 non-null    datetime64[ns]
 3   Time of Restoration           307 non-null    object
 4   Area Affected                 307 non-null    object
 5   NERC Region                   304 non-null    object
 6   Event Type                    307 non-null    object
 7   Demand Loss (MW)              236 non-null    object
 8   Number of Customers Affected  262 non-null    object
dtypes: datetime64[ns](1), object(8)
memory usage: 22.7+ KB

In [258]:
df_11['Date Event Began'] = pd.to_datetime(df_11['Date Event Began'], errors='coerce')
df_11 = df_11.dropna(subset=['Date Event Began'])
df_11.reset_index(drop=True, inplace=True)
df_11.drop(columns=['Time Event Began', 'Time of Restoration'], inplace=True)

df_11.head(10)

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2011-01-11,2011-01-11,"Athens, New York",NPCC,Electrical Fault at Generator,0,0
1,2011-01-12,2011-01-12,Massachusetts,NPCC,Winter Storm,NaN,80000
2,2011-01-13,2011-01-13,North Florida,FRCC,Firm System Load Shed,150,20900
3,2011-01-18,2011-01-18,"Whitman, Auburn St Substation, Massachusetts",NPCC,Vandalism,0,0
4,2011-01-23,2011-01-23,"Franklin County, Idaho",WECC,Vandalism,0,0
5,2011-01-24,2011-01-24,"Newman Power Plant, Texas",WECC,Suspicious Activity,0,0
6,2011-01-25,2011-01-25,"Newark, Delaware",RFC,Vandalism,0,0
7,2011-01-26,2011-01-27,"Carson City, Nevada",WECC,Suspected Telecommunications Attack,0,0
8,2011-01-26,2011-01-27,Michigan,RFC,Vandalism,0,0
9,2011-01-26,2011-01-31,"Montgomery and Prince George's County, Marylan...",RFC,Winter Storm,NaN,210000

In [259]:
df_02 = df_02[['Date Event Began', 'Date of Restoration', 'Area Affected', 'NERC Region', 'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected']]
df_03 = df_03[['Date Event Began', 'Date of Restoration', 'Area Affected', 'NERC Region', 'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected']]
df_04 = df_04[['Date Event Began', 'Date of Restoration', 'Area Affected', 'NERC Region', 'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected']]
df_05 = df_05[['Date Event Began', 'Date of Restoration', 'Area Affected', 'NERC Region', 'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected']]
df_06 = df_06[['Date Event Began', 'Date of Restoration', 'Area Affected', 'NERC Region', 'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected']]
df_07 = df_07[['Date Event Began', 'Date of Restoration', 'Area Affected', 'NERC Region', 'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected']]
df_08 = df_08[['Date Event Began', 'Date of Restoration', 'Area Affected', 'NERC Region', 'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected']]
df_09 = df_09[['Date Event Began', 'Date of Restoration', 'Area Affected', 'NERC Region', 'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected']]
df_10 = df_10[['Date Event Began', 'Date of Restoration', 'Area Affected', 'NERC Region', 'Event Type', 'Demand Loss (MW)', 'Number of Customers Affected']]

In [260]:
df_12 = pd.read_excel(input, header=1, sheet_name='2012')
df_12['Date Event Began'] = pd.to_datetime(df_12['Date Event Began'], errors='coerce')
df_12 = df_12.dropna(subset=['Date Event Began'])
df_12.reset_index(drop=True, inplace=True)
df_12.drop(columns=['Time Event Began', 'Time of Restoration'], inplace=True)

df_12

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2012-01-04,2012-01-04 00:00:00,"Tacoma, Washington",WECC,Suspected physical attack,NaN,NaN
1,2012-01-05,2012-01-05 00:00:00,"CSWS/AEP West territory, Oklahoma",SPP,Sabotage,0,0
2,2012-01-05,2012-01-05 00:00:00,"Creek County, Oklahoma",SPP,Suspected physical attack,NaN,NaN
3,2012-01-09,2012-01-09 00:00:00,"Watertown, Connecticut",NPCC,Vandalism,NaN,NaN
4,2012-01-09,2012-01-11 00:00:00,Louisiana,SERC,Load Shed,150,1
...,...,...,...,...,...,...,...
191,2012-12-17,2012-12-17 00:00:00,"Tacoma, Washington",WECC,Suspected Physical Attack,0,0
192,2012-12-25,2012-12-28 00:00:00,Arkansas; Louisiana; Mississippi; Texas,SPP,Severe Weather - Winter Storm,Unknown,242509
193,2012-12-25,2012-12-26 00:00:00,"Houston, Texas",TRE,"Severe Weather - Cold Front, High Winds",294,262000
194,2012-12-26,2012-12-26 00:00:00,"Stantonsburg, North Carolina",SERC,Severe Weather - Thunderstorm,3,1200
195,2012-12-31,2012-12-31 00:00:00,North Carolina,SERC,Transmission Interruption,40,12000

In [261]:
df_13 = pd.read_excel(input, header=1, sheet_name='2013')
df_13['Date Event Began'] = pd.to_datetime(df_13['Date Event Began'], errors='coerce')
df_13 = df_13.dropna(subset=['Date Event Began'])
df_13.reset_index(drop=True, inplace=True)
df_13.drop(columns=['Time Event Began', 'Time of Restoration'], inplace=True)

df_13

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2013-01-07,2013-01-07 00:00:00,"Denton, Maryland",RFC,Physcial Attack; Vandalism,Unknown,Unknown
1,2013-01-16,2013-01-16 00:00:00,"Denton, Maryland",RFC,Physcial Attack; Vandalism,Unknown,Unknown
2,2013-01-16,2013-01-16 00:00:00,"San Juan County, New Mexico",WECC,Suspected Physical Attack,0,0
3,2013-01-16,2013-01-17 00:00:00,"Webster County, Iowa",MRO,Physical Attack,NaN,NaN
4,2013-01-17,2013-01-20 00:00:00,"Southwest Virginia, Southern West Virginia",RFC,Severe Weather - Winter Storm,Unknown,127000
...,...,...,...,...,...,...,...
169,2013-12-22,2013-12-28 00:00:00,"Southern Lower Penninsula, Michigan",RFC,Severe Weather - Ice/Snow,Unknown,50000
170,2013-12-23,2013-12-25 00:00:00,Central Maine Maine,NPCC,Severe Weather - Ice/Snow,Unknown,52500
171,2013-12-27,2013-12-27 00:00:00,Gilabend Arizona,WECC,Physical Attack,NaN,NaN
172,2013-12-30,2013-12-30 00:00:00,Salt Lake County Utah,WECC,Physical Attack,NaN,NaN
173,2013-12-30,2014-01-01 00:00:00,North of Roosevelt lake Arizona,WECC,Physical Attack,NaN,NaN

In [262]:
df_14 = pd.read_excel(input, header=1, sheet_name='2014')
df_14['Date Event Began'] = pd.to_datetime(df_14['Date Event Began'], errors='coerce')
df_14 = df_14.dropna(subset=['Date Event Began'])
df_14.reset_index(drop=True, inplace=True)
df_14.drop(columns=['Time Event Began', 'Time of Restoration'], inplace=True)

df_14

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2014-01-06,2014-01-06 00:00:00,District of Columbia,RFC,Voltage Reduction due to Severe Weather - Cold,Unknown,Unknown
1,2014-01-06,2014-01-06 00:00:00,Unknown,RFC,Voltage Reduction due to Severe Weather - Cold,Unknown,Unknown
2,2014-01-06,2014-01-06 00:00:00,Delaware,RFC,Voltage Reduction due to Severe Weather - Cold,Unknown,Unknown
3,2014-01-06,2014-01-07 00:00:00,Unknown,RFC,Public Appeal due to Severe Weather - Cold,Unknown,Unknown
4,2014-01-06,2014-01-06 00:00:00,Pennsylvania,RFC,Voltage Reduction due to Severe Weather - Cold,200,62000
...,...,...,...,...,...,...,...
209,2014-12-11,2014-12-11 00:00:00,"Portland, Oregon",WECC,Severe Weather- High Winds,250,85470
210,2014-12-11,2014-12-12 00:00:00,"Kitsap, Thurston, Whatcom counties Washington",WECC,Severe Weather- High Winds,116,264000
211,2014-12-17,2014-12-17 00:00:00,Washington,WECC,Suspected Physical Attack,Unknown,Unknown
212,2014-12-30,2014-12-31 00:00:00,"New Hampshire, Massachusetts, Maine, Rhode Isl...",NPCC,Suspected Cyber Attack,Unknown,Unknown
213,2014-12-30,2015-01-01 00:00:00,Northern California,WECC,Severe Weather- High Winds,127,84500

In [263]:
df_15 = pd.read_excel(input, header=1, sheet_name='2015')
df_15['Date Event Began'] = pd.to_datetime(df_15['Date Event Began'], errors='coerce')
df_15 = df_15.dropna(subset=['Date Event Began'])
df_15.reset_index(drop=True, inplace=True)
df_15.drop(columns=['Month', 'Time Event Began', 'Time of Restoration', 'Alert Criteria'], inplace=True)

df_15

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2015-01-07,2015-01-08 00:00:00,Tennessee,SERC,Severe Weather - Winter,Unknown,Unknown
1,2015-01-07,2015-01-08 00:00:00,"Tennessee, Kentucky, Virginia, North Carolina,...",SERC,Severe Weather - Winter,Unknown,Unknown
2,2015-01-22,2015-01-22 00:00:00,"Portland, Oregon",WECC,Vandalism,Unknown,Unknown
3,2015-01-26,2015-01-26 00:00:00,"Cave Junction, Oregon",WECC,Vandalism,Unknown,Unknown
4,2015-01-27,2015-01-27 00:00:00,"Kountze, Texas",SERC,Sabotage,0,0
...,...,...,...,...,...,...,...
138,2015-12-27,2015-12-28 00:00:00,Oklahoma,SPP,Severe Weather,Unknown,54476
139,2015-12-27,Unknown,Oklahoma,SPP,Severe Weather,Unknown,50500
140,2015-12-29,2015-12-29 00:00:00,Maine,NPCC,Sabotage,0,0
141,2015-12-31,2015-12-31 00:00:00,Oklahoma: Blaine County;,SPP,Severe Weather,8,1500
142,2015-12-31,Unknown,Missouri,SERC,Sabotage,0,0

In [264]:
df_16 = pd.read_excel(input, header=1, sheet_name='2016')
df_16['Date Event Began'] = pd.to_datetime(df_16['Date Event Began'], errors='coerce')
df_16 = df_16.dropna(subset=['Date Event Began'])
df_16.reset_index(drop=True, inplace=True)
df_16.drop(columns=['Month', 'Time Event Began', 'Time of Restoration', 'Alert Criteria'], inplace=True)

df_16

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2016-01-04,2016-01-05 00:00:00,Wisconsin: Milwaukee County;,MRO,Sabotage,0,0
1,2016-01-10,2016-01-11 00:00:00,Maine: Connecticut: Massachusetts: Vermont: Ne...,NPCC,Weather,Unknown,59859
2,2016-01-11,2016-01-11 00:00:00,Pennsylvania: Chester County;,RFC,Vandalism,0,0
3,2016-01-14,2016-01-14 00:00:00,Delaware:,RFC,Vandalism,0,0
4,2016-01-17,2016-01-17 00:00:00,Utah: Salt Lake County;,WECC,Sabotage,0,0
...,...,...,...,...,...,...,...
136,2016-12-16,12/16/2016,Oregon: Multnomah County;,WECC,Vandalism,0,0
137,2016-12-26,12/26/2016,Washington:,WECC,Vandalism,0,0
138,2016-12-28,12/31/2016,California:,WECC,Fuel Supply Deficiency,0,0
139,2016-12-30,12/30/2016,Vermont: Chittenden County;,NPCC,Other,0,0
140,2016-12-30,12/30/2016,Maine:,NPCC,Weather or Natural Disaster,Unknown,85263

In [265]:
df_17 = pd.read_excel(input, header=1, sheet_name='2017')
df_17['Date Event Began'] = pd.to_datetime(df_17['Date Event Began'], errors='coerce')
df_17 = df_17.dropna(subset=['Date Event Began'])
df_17.reset_index(drop=True, inplace=True)
df_17.drop(columns=['Month', 'Time Event Began', 'Time of Restoration', 'Alert Criteria'], inplace=True)

df_17

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2017-01-05,01/05/2017,Florida: Martin County;,FRCC,Suspected Physical Attack,0,0
1,2017-01-08,01/13/2017,California,WECC,Severe Weather,Unknown,106000
2,2017-01-08,Unknown,California,WECC,Fuel Supply Deficiency,0,0
3,2017-01-10,01/13/2017,California,WECC,Severe Weather,Unknown,87000
4,2017-01-15,01/15/2017,California: Los Angeles County;,WECC,Transmission Disruption,176,126000
...,...,...,...,...,...,...,...
145,2017-12-18,12/18/2017,Mississippi:,SERC,Vandalism,0,0
146,2017-12-19,12/19/2017,Florida: Alachua County;,FRCC,Vandalism,0,0
147,2017-12-29,12/29/2017,Texas: Calhoun County;,TRE,Suspicious Activity,Unknown,Unknown
148,2017-12-29,Unknown,New York: Tompkins County;,NPCC,Fuel Supply Deficiency,210,Unknown
149,2017-12-31,01/01/2018,Colorado:,WECC,Vandalism,0,0

In [266]:
df_18 = pd.read_excel(input, header=1, sheet_name='2018')
df_18['Date Event Began'] = pd.to_datetime(df_18['Date Event Began'], errors='coerce')
df_18 = df_18.dropna(subset=['Date Event Began'])
df_18.reset_index(drop=True, inplace=True)
df_18.drop(columns=['Month', 'Time Event Began', 'Time of Restoration', 'Alert Criteria'], inplace=True)

df_18

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2018-01-01,01/02/2018,Tennessee:,SERC,Severe Weather,Unknown,Unknown
1,2018-01-01,Unknown,Texas:,TRE,Severe Weather,Unknown,Unknown
2,2018-01-01,01/02/2018,Tennessee:,SERC,System Operations,Unknown,Unknown
3,2018-01-02,02/12/2018,New York: Niagara County;,NPCC,Fuel Supply Deficiency,675,Unknown
4,2018-01-02,Unknown,South Carolina:,SERC,Severe Weather,0,717000
...,...,...,...,...,...,...,...
215,2018-12-26,01/03/2019,California: Kern County;,WECC,Vandalism,0,0
216,2018-12-27,12/27/2018,New York: New York County;,NPCC,Transmission Interruption,Unknown,Unknown
217,2018-12-27,12/27/2018,"Maryland: Montgomery County, Prince George's C...",RF,System Operations,0,0
218,2018-12-27,12/27/2018,California: Kern County;,WECC,Vandalism,0,0
219,2018-12-30,12/30/2018,Washington: King County;,WECC,System Operations,0,0

In [267]:
df_19 = pd.read_excel(input, header=1, sheet_name='2019')
df_19['Date Event Began'] = pd.to_datetime(df_19['Date Event Began'], errors='coerce')
df_19 = df_19.dropna(subset=['Date Event Began'])
df_19.reset_index(drop=True, inplace=True)
df_19.drop(columns=['Month', 'Time Event Began', 'Time of Restoration', 'Alert Criteria'], inplace=True)

df_19

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2019-01-05,01/05/2019,Washington:,WECC,System Operations,0,Unknown
1,2019-01-06,01/09/2019,Washington:,WECC,Severe Weather,230,230000
2,2019-01-06,01/06/2019,California: Sacramento County;,WECC,Severe Weather,300,90382
3,2019-01-06,01/06/2019,"Washington: King County, Thurston County, Pier...",WECC,Severe Weather,Unknown,230000
4,2019-01-07,01/07/2019,Michigan:,RF,System Operations,0,0
...,...,...,...,...,...,...,...
273,2019-12-18,12/18/2019,Texas: Nueces County;,TRE,System Operations,0,0
274,2019-12-19,12/19/2019,Nebraska:,MRO,System Operations,0,0
275,2019-12-24,12/24/2019,Illinois:,SERC,Suspicious Activity,0,0
276,2019-12-31,12/31/2019,Washington:,WECC,Vandalism,0,0
277,2019-12-31,01/01/2020,Texas: Nueces County;,TRE,Transmission Interruption,25,0

In [268]:
df_20 = pd.read_excel(input, header=1, sheet_name='2020')
df_20['Date Event Began'] = pd.to_datetime(df_20['Date Event Began'], errors='coerce')
df_20 = df_20.dropna(subset=['Date Event Began'])
df_20.reset_index(drop=True, inplace=True)
df_20.drop(columns=['Month', 'Time Event Began', 'Time of Restoration', 'Alert Criteria'], inplace=True)

df_20

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2020-01-09,01/09/2020,Arkansas: Yell County;,SPP RE,Severe Weather/Transmission Interruption,0,0
1,2020-01-09,01/10/2020,Washington: King County;,WECC,Suspicious Activity,0,0
2,2020-01-09,01/09/2020,Minnesota: North Dakota: Wisconsin:,MRO,System Operations,0,0
3,2020-01-09,01/09/2020,Arkansas:,SPP RE,System Operations,Unknown,Unknown
4,2020-01-10,Unknown,Tennessee: Hamilton County;,SERC,Suspicious Activity,Unknown,Unknown
...,...,...,...,...,...,...,...
378,2020-12-24,Unknown,"Pennsylvania: Bucks County, Chester County, De...",RF,Severe Weather/Distribution Interruption,Unknown,68114
379,2020-12-25,12/25/2020,California:,WECC,Vandalism,0,0
380,2020-12-25,12/25/2020,Ohio: Kentucky:,RF,Suspicious Activity,0,0
381,2020-12-25,12/25/2020,Connecticut: Maine: New Hampshire: Massachuset...,NPCC,Severe Weather,Unknown,19000
382,2020-12-28,12/29/2020,Virginia:,SERC,Vandalism,0,0

In [269]:
df_21 = pd.read_excel(input, header=1, sheet_name='2021')
df_21['Date Event Began'] = pd.to_datetime(df_21['Date Event Began'], errors='coerce')
df_21 = df_21.dropna(subset=['Date Event Began'])
df_21.reset_index(drop=True, inplace=True)
df_21.drop(columns=['Month', 'Time Event Began', 'Time of Restoration', 'Alert Criteria'], inplace=True)

df_21

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2021-01-01,01/01/2021,California: Alameda County;,WECC,Vandalism,0,0
1,2021-01-02,01/02/2021,California: Butte County;,WECC,System Operations,8,5803
2,2021-01-04,01/04/2021,Pennsylvania:,RF,Transmission Interruption,6,3825
3,2021-01-08,01/08/2021,Arkansas: Prairie County;,SERC,Sabotage,Unknown,1908
4,2021-01-10,01/13/2021,"Texas: Anderson County, Angelina County, Dalla...",TRE,Severe Weather,Unknown,188000
...,...,...,...,...,...,...,...
382,2021-12-24,12/24/2021,Texas: Rusk County;,TRE,System Operations,Unknown,Unknown
383,2021-12-27,01/01/2022,California:,WECC,Severe Weather,381,115830
384,2021-12-27,12/30/2021,California: Humboldt County;,WECC,System Operations,120,65994
385,2021-12-29,12/29/2021,Nevada: Clark County;,WECC,System Operations,0,0
386,2021-12-30,Unknown,"Missouri: Adair County, Putnam County;",SERC,Vandalism,0,0

In [270]:
df_22 = pd.read_excel(input, header=1, sheet_name='2022')
df_22['Date Event Began'] = pd.to_datetime(df_22['Date Event Began'], errors='coerce')
df_22 = df_22.dropna(subset=['Date Event Began'])
df_22.reset_index(drop=True, inplace=True)
df_22.drop(columns=['Month', 'Time Event Began', 'Time of Restoration', 'Alert Criteria'], inplace=True)

df_22

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2022-01-01,01/01/2022,Washington: Thurston County;,WECC,System Operations,0,0
1,2022-01-01,01/02/2022,Washington: Thurston County;,WECC,System Operations,0,0
2,2022-01-01,Unknown,Georgia: Clayton County;,SERC,Vandalism,0,0
3,2022-01-01,01/01/2022,New Hampshire: Merrimack County;,NPCC,Suspicious Activity,2,845
4,2022-01-02,01/02/2022,California: Tuolumne County;,WECC,Severe Weather,3,1706
...,...,...,...,...,...,...,...
385,2022-12-29,Unknown,Ohio:,RF,Vandalism,2600,Unknown
386,2022-12-30,12/30/2022,Oregon: Sherman County;,WECC,Transmission Interruption,0,0
387,2022-12-30,Unknown,Minnesota: Washington County;,MRO,Transmission Interruption,Unknown,Unknown
388,2022-12-31,01/03/2023,Nevada:,WECC,Severe Weather,Unknown,3500
389,2022-12-31,01/01/2023,California: Sacramento County;,WECC,Severe Weather,Unknown,161000

In [271]:
df_23 = pd.read_excel(input, header=1, sheet_name='2023')
df_23['Date Event Began'] = pd.to_datetime(df_23['Date Event Began'], errors='coerce')
df_23 = df_23.dropna(subset=['Date Event Began'])
df_23.reset_index(drop=True, inplace=True)
df_23.drop(columns=['Event Year', 'Event Month', 'Time Event Began', 'Time of Restoration', 'Alert Criteria'], inplace=True)

df_23

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2023-01-01,01/01/2023,California: Riverside County;,WECC,Vandalism,0,0
1,2023-01-01,01/01/2023,California: Sacramento County;,WECC,System Operations,0,0
2,2023-01-01,01/01/2023,Florida: Citrus County;,SERC,Vandalism,19,3509
3,2023-01-02,01/03/2023,Texas: Dallas County;,TRE,Vandalism,0,0
4,2023-01-02,01/02/2023,New Mexico:,WECC,Vandalism,432,0
...,...,...,...,...,...,...,...
162,2023-06-29,Unknown,Indiana,RF,- Weather or natural disaster,Unknown,140000
163,2023-06-28,2023-06-28 00:00:00,Georgia,SERC,- Vandalism - Theft,0,0
164,2023-06-22,2023-06-22 00:00:00,Louisiana,SERC,- Transmission equipment failure,17,6242
165,2023-06-20,2023-06-20 00:00:00,Louisiana,SERC,- Transmission equipment failure,0,0
166,2023-06-30,Unknown,Connecticut,NPCC,- Unknown,0,0

In [272]:
df_big = pd.concat([df_02, df_03, df_04, df_05, df_06, df_07, df_08, df_09, df_10, df_11, 
                    df_12, df_13, df_14, df_15, df_16, df_17, df_18, df_19, df_20, df_21, df_22, df_23], ignore_index=True)

# df_big.to_excel('grid_outages.xlsx')
df_big.head()

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2002-01-30,2002-02-07 12:00:00,Oklahoma,SPP,Ice Storm,500,1881134
1,2002-01-29,NaN,Metropolitan Kansas City Area,SPP,Ice Storm,500-600,270000
2,2002-01-30,2002-02-10 21:00:00,Missouri,SPP,Ice Storm,210,95000
3,2002-02-27,2002-02-27 11:35:00,California,WSCC,Interruption of Firm Load,300,255000
4,2002-03-09,2002-03-11 12:00:00,Lower Peninsula of Michigan,ECAR,Severe Weather,190,190000

In [273]:
df_big['Date Event Began'] = pd.to_datetime(df_big['Date Event Began'], errors='coerce')

df_big['Date of Restoration'] = pd.to_datetime(df_big['Date of Restoration'], errors='coerce')
# df_big = df_big.dropna(subset=['Date of Restoration'])
df_big.head()

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected
0,2002-01-30,2002-02-07 12:00:00,Oklahoma,SPP,Ice Storm,500,1881134
1,2002-01-29,NaT,Metropolitan Kansas City Area,SPP,Ice Storm,500-600,270000
2,2002-01-30,2002-02-10 21:00:00,Missouri,SPP,Ice Storm,210,95000
3,2002-02-27,2002-02-27 11:35:00,California,WSCC,Interruption of Firm Load,300,255000
4,2002-03-09,2002-03-11 12:00:00,Lower Peninsula of Michigan,ECAR,Severe Weather,190,190000

In [274]:
df_big.dtypes

Date Event Began                datetime64[ns]
Date of Restoration             datetime64[ns]
Area Affected                           object
NERC Region                             object
Event Type                              object
Demand Loss (MW)                        object
Number of Customers Affected            object
dtype: object

In [275]:
df_big.reset_index(drop=True, inplace=True)

# # df_big.head(10)
# df_big.dtypes

In [276]:
import us

states = [state.name for state in us.states.STATES_AND_TERRITORIES]
abbreviations = [state.abbr for state in us.states.STATES_AND_TERRITORIES]
all_states = states + abbreviations

In [277]:
def extract_state_names(text, all_states):
    for state in all_states:
        if state in text:
            return state

In [278]:
df_big['State Names'] = df_big['Area Affected'].apply(lambda x: extract_state_names(x, all_states))

In [279]:
df_big.to_excel('grid_outages0.xlsx')

df_big.head()

,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,State Names
0,2002-01-30,2002-02-07 12:00:00,Oklahoma,SPP,Ice Storm,500,1881134,Oklahoma
1,2002-01-29,NaT,Metropolitan Kansas City Area,SPP,Ice Storm,500-600,270000,Kansas
2,2002-01-30,2002-02-10 21:00:00,Missouri,SPP,Ice Storm,210,95000,Missouri
3,2002-02-27,2002-02-27 11:35:00,California,WSCC,Interruption of Firm Load,300,255000,California
4,2002-03-09,2002-03-11 12:00:00,Lower Peninsula of Michigan,ECAR,Severe Weather,190,190000,Michigan

In [280]:
df_states = pd.read_excel('grid_outages0.xlsx')
df_states.head()

,Unnamed: 0,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,State Names
0,0,2002-01-30,2002-02-07 12:00:00,Oklahoma,SPP,Ice Storm,500,1881134,Oklahoma
1,1,2002-01-29,NaT,Metropolitan Kansas City Area,SPP,Ice Storm,500-600,270000,Kansas
2,2,2002-01-30,2002-02-10 21:00:00,Missouri,SPP,Ice Storm,210,95000,Missouri
3,3,2002-02-27,2002-02-27 11:35:00,California,WSCC,Interruption of Firm Load,300,255000,California
4,4,2002-03-09,2002-03-11 12:00:00,Lower Peninsula of Michigan,ECAR,Severe Weather,190,190000,Michigan

In [281]:
state_abbreviations = {state.abbr: state.name for state in us.states.STATES}

In [282]:
def convert_abbreviations_to_full_names(state):
    if state in state_abbreviations:
        return state_abbreviations[state]
    else:
        return state

In [283]:
df_states['State Names'] = df_states['State Names'].apply(convert_abbreviations_to_full_names)

In [284]:
df_states.head()

,Unnamed: 0,Date Event Began,Date of Restoration,Area Affected,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,State Names
0,0,2002-01-30,2002-02-07 12:00:00,Oklahoma,SPP,Ice Storm,500,1881134,Oklahoma
1,1,2002-01-29,NaT,Metropolitan Kansas City Area,SPP,Ice Storm,500-600,270000,Kansas
2,2,2002-01-30,2002-02-10 21:00:00,Missouri,SPP,Ice Storm,210,95000,Missouri
3,3,2002-02-27,2002-02-27 11:35:00,California,WSCC,Interruption of Firm Load,300,255000,California
4,4,2002-03-09,2002-03-11 12:00:00,Lower Peninsula of Michigan,ECAR,Severe Weather,190,190000,Michigan

In [285]:
df_states.drop(['Area Affected'], axis=1, inplace=True)
df_states.head()

,Unnamed: 0,Date Event Began,Date of Restoration,NERC Region,Event Type,Demand Loss (MW),Number of Customers Affected,State Names
0,0,2002-01-30,2002-02-07 12:00:00,SPP,Ice Storm,500,1881134,Oklahoma
1,1,2002-01-29,NaT,SPP,Ice Storm,500-600,270000,Kansas
2,2,2002-01-30,2002-02-10 21:00:00,SPP,Ice Storm,210,95000,Missouri
3,3,2002-02-27,2002-02-27 11:35:00,WSCC,Interruption of Firm Load,300,255000,California
4,4,2002-03-09,2002-03-11 12:00:00,ECAR,Severe Weather,190,190000,Michigan

In [286]:
# df_states.to_excel('grid_data_clean0.xlsx')

In [287]:
consolidated_data = df_states['Event Type'].value_counts()
consolidated_data.head(40)

Severe Weather                                878
Vandalism                                     511
System Operations                             410
Suspicious Activity                           193
Transmission Interruption                     177
Severe Weather - Thunderstorms                 97
Suspected Physical Attack                      87
Severe Thunderstorms                           70
Fuel Supply Deficiency                         59
Winter Storm                                   51
Severe Weather/Transmission Interruption       48
Actual Physical Attack                         45
Ice Storm                                      42
Physical Attack - Vandalism                    40
Sabotage                                       35
High Winds                                     33
Physical Attack                                30
Thunderstorms                                  30
Electrical System Separation (Islanding)       30
Public Appeal to Reduce Electricity Usage      27
Physical Attack; Vandalism                     24
Actual Physical Attack/Vandalism               24
Cyber Event                                    23
Severe Storm                                   22
Made Public Appeals                            22
Severe Weather - Hurricane Sandy               21
Suspected Physical Attack - Vandalism          16
Generation Inadequacy                          15
Weather                                        14
Wind Storm                                     14
Severe Storms                                  13
Severe Weather - Winter Storm                  13
Suspected Cyber Attack                         13
Voltage Reduction                              13
Electrical System Separation                   12
Severe Thunderstorm                            12
Public Appeal due to Severe Weather - Cold     12
Load Shedding                                  11
Fuel Supply Emergency - Coal                   11
Severe Weather - Winter                        11
Name: Event Type, dtype: int64

In [288]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Storm', 'Severe Weather')

In [289]:
df_states['Event Type'] = df_states['Event Type'].replace('Weather', 'Severe Weather')

In [290]:
df_states['Event Type'] = df_states['Event Type'].replace('Major Storm', 'Severe Weather')

In [291]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather - Snow/Ice', 'Winter Storm')

In [292]:
df_states['Event Type'] = df_states['Event Type'].replace('Ice Storm', 'Winter Storm')

In [293]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather - Ice/Snow', 'Winter Storm')

In [294]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather - Winter Storm', 'Winter Storm')

In [295]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather - Thunderstorms', 'Thunderstorms')

In [296]:
df_states['Event Type'] = df_states['Event Type'].replace('Physical Attack - Vandalism', 'Physical Attack')

In [297]:
df_states['Event Type'] = df_states['Event Type'].replace('Suspected Physical Attack', 'Physical Attack')

In [298]:
df_states['Event Type'] = df_states['Event Type'].replace('Actual Physical Attack', 'Physical Attack')

In [299]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Thunderstorms', 'Thunderstorms')

In [300]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Thunderstorm', 'Thunderstorms')

In [301]:
df_states['Event Type'] = df_states['Event Type'].replace('Actual Physical Attack/Vandalism', 'Physical Attack')

In [302]:
df_states['Event Type'] = df_states['Event Type'].replace('Physical Attack/Vandalism', 'Physical Attack')

In [303]:
df_states['Event Type'] = df_states['Event Type'].replace('Physcial Attack; Vandalism', 'Physical Attack')

In [304]:
df_states['Event Type'] = df_states['Event Type'].replace('Sabotage', 'Physical Attack')

In [305]:
df_states['Event Type'] = df_states['Event Type'].replace('Suspected Physical Attack - Vandalism', 'Physical Attack')

In [306]:
df_states['Event Type'] = df_states['Event Type'].replace('Physical Attack; Vandalism', 'Physical Attack')

In [307]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather/Distribution Interruption', 'Severe Weather')

In [308]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather/Transmission Interruption', 'Severe Weather')

In [309]:
df_states['Event Type'] = df_states['Event Type'].replace('High Winds', 'Severe Weather')

In [310]:
df_states['Event Type'] = df_states['Event Type'].replace('Wind Storm', 'Severe Weather')

In [311]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather - Wind', 'Severe Weather')

In [312]:
df_states['Event Type'] = df_states['Event Type'].replace('High Winds and Rain', 'Severe Weather')

In [313]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather/Transmisison Interruption', 'Severe Weather')

In [314]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather/Transmisison Interruption', 'Severe Weather')

In [315]:
df_states['Event Type'] = df_states['Event Type'].replace('- Weather or natural disaster', 'Severe Weather')

In [316]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Storm', 'Severe Weather')

In [317]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Storms', 'Severe Weather')

In [318]:
df_states['Event Type'] = df_states['Event Type'].replace('Strong Thunderstorms', 'Thunderstorms')

In [319]:
df_states['Event Type'] = df_states['Event Type'].replace('Suspected Cyber Attack', 'Cyber Event')

In [320]:
df_states['Event Type'] = df_states['Event Type'].replace('Severe Weather - Winter', 'Winter Storm')

In [321]:
df_states['Event Type'] = df_states['Event Type'].replace('Ice/Snow Storm', 'Winter Storm')

In [322]:
df_states['Event Type'] = df_states['Event Type'].replace('Islanding', 'Electrical System Separation (Islanding)')

In [323]:
df_states['Event Type'] = df_states['Event Type'].replace('Electrical System Separation', 'Electrical System Separation (Islanding)')

In [324]:
df_states['Event Type'] = df_states['Event Type'].replace('Voltage Reduction due to Severe Weather - Cold', 'Voltage Reduction')

In [325]:
df_states['Event Type'] = df_states['Event Type'].replace('Voltage Reduction/Load Shed', 'Voltage Reduction')

In [326]:
df_states['Event Type'] = df_states['Event Type'].replace('Load Shedding', 'Voltage Reduction')

In [327]:
df_states['Event Type'] = df_states['Event Type'].replace('Vandalism', 'Physical Attack')

In [328]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Hurricane.*', 'Natural Disaster', regex=True)

In [329]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Earthquake.*', 'Natural Disaster', regex=True)

In [330]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Winter.*', 'Winter Storm', regex=True)

In [331]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Ice.*', 'Winter Storm', regex=True)

In [332]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Snow.*', 'Winter Storm', regex=True)

In [333]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Vandalism.*', 'Physical Attack', regex=True)

In [334]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Physical.*', 'Physical Attack', regex=True)

In [335]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Generation.*', 'Voltage Reduction', regex=True)

In [336]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Load.*', 'Voltage Reduction', regex=True)

In [337]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Severe.*', 'Severe Weather', regex=True)

In [338]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Storm.*', 'Severe Weather', regex=True)

In [339]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Storms.*', 'Severe Weather', regex=True)

In [340]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Thunderstorm.*', 'Severe Weather', regex=True)

In [341]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Winds.*', 'Severe Weather', regex=True)

In [342]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Wind.*', 'Severe Weather', regex=True)

In [343]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Islanding.*', 'Electrical System Separation (Islanding)', regex=True)

In [344]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Suspicious.*', 'Suspicious Activity', regex=True)

In [345]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Cyber.*', 'Cyber Event', regex=True)

In [346]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Fuel.*', 'Fuel Supply Deficiency', regex=True)

In [347]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Voltage.*', 'Voltage Reduction', regex=True)

In [348]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Failure.*', 'Equipment Failure', regex=True)

In [349]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Malfunction.*', 'Equipment Failure', regex=True)

In [350]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Interruption.*', 'Transmission Interruption', regex=True)

In [351]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Public.*', 'Public Appeals', regex=True)

In [352]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Weather.*', 'Severe Weather', regex=True)

In [353]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Tornado.*', 'Natural Disaster', regex=True)

In [354]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Attack.*', 'Physical Attack', regex=True)

In [355]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*attack.*', 'Physical Attack', regex=True)

In [356]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Lightning.*', 'Severe Weather', regex=True)

In [357]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Vandalsim.*', 'Physical Attack', regex=True)

In [358]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Sabotage.*', 'Physical Attack', regex=True)

In [359]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Tripped.*', 'Unit Tripped', regex=True)

In [360]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Fire.*', 'Fire', regex=True)

In [361]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Equipment.*', 'Equipment Failure', regex=True)

In [362]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*equipment.*', 'Equipment Failure', regex=True)

In [363]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Fault.*', 'Equipment Failure', regex=True)

In [364]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Transmission.*', 'Transmission Interruption', regex=True)

In [365]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Flood.*', 'Natural Disaster', regex=True)

In [366]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Fire.*', 'Natural Disaster', regex=True)

In [367]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Heat.*', 'Severe Weather', regex=True)

In [368]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Deficiency.*', 'Fuel Supply Deficiency', regex=True)

In [369]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Unit.*', 'Unit Tripped', regex=True)

In [370]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Unknown.*', 'Other', regex=True)

In [371]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Electric.*', 'Electrical System Separation (Islanding)', regex=True)

In [372]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Highwinds.*', 'Severe Weather', regex=True)

In [373]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*reductions.*', 'Voltage Reduction', regex=True)

In [374]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Resources.*', 'Fuel Supply Deficiency', regex=True)

In [375]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Wildfire.*', 'Natural Disaster', regex=True)

In [376]:
df_states['Event Type'] = df_states['Event Type'].str.replace(r'.*Tropical.*', 'Natural Disaster', regex=True)

In [377]:
counts = df_states['Event Type'].value_counts()
mask = df_states['Event Type'].isin(counts[counts == 1].index)
df_states.loc[mask, 'Event Type'] = 'Other'

In [378]:
df_states['Event Type'].value_counts()

Severe Weather                              1590
Physical Attack                              874
System Operations                            410
Transmission Interruption                    207
Suspicious Activity                          199
Voltage Reduction                            167
Natural Disaster                             123
Fuel Supply Deficiency                       103
Public Appeals                                82
Electrical System Separation (Islanding)      61
Equipment Failure                             45
Cyber Event                                   41
Other                                         27
Unit Tripped                                  20
Name: Event Type, dtype: int64

In [379]:
df_states.dtypes
# df_states.head(30)

Unnamed: 0                               int64
Date Event Began                datetime64[ns]
Date of Restoration             datetime64[ns]
NERC Region                             object
Event Type                              object
Demand Loss (MW)                        object
Number of Customers Affected            object
State Names                             object
dtype: object

In [380]:
df_states.drop(columns='Unnamed: 0', inplace=True)
df_states.dtypes

Date Event Began                datetime64[ns]
Date of Restoration             datetime64[ns]
NERC Region                             object
Event Type                              object
Demand Loss (MW)                        object
Number of Customers Affected            object
State Names                             object
dtype: object

In [381]:
df_states['Number of Customers Affected'].value_counts()

0          911
Unknown    497
0          315
-           27
UNK         26
          ...
53064        1
931000       1
181700       1
14500        1
6242         1
Name: Number of Customers Affected, Length: 1370, dtype: int64

In [382]:
print(df_states['Number of Customers Affected'].isna())

df_states['Number of Customers Affected'].replace(["UNK", "-"], "Unknown", inplace=True)

0       False
1       False
2       False
3       False
4       False
        ...
3944    False
3945    False
3946    False
3947    False
3948    False
Name: Number of Customers Affected, Length: 3949, dtype: bool

In [383]:
df_states['Number of Customers Affected'].value_counts()

0          911
Unknown    550
0          315
50000       25
1           17
          ...
931000       1
181700       1
14500        1
71500        1
6242         1
Name: Number of Customers Affected, Length: 1368, dtype: int64

In [384]:
df_states.to_excel('grid_cleaned_1.xlsx')